---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: abs-secret
  namespace: media
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-cluster-secretstore
  target:
    name: abs-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        JWT_SECRET_KEY: "{{ .jwt_secret }}"
  data:
    - secretKey: jwt_secret
      remoteRef:
        key: media/abs/credentials
        property: jwt_secret
