---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-webhook-secret
  namespace: observability
spec:
  secretStoreRef:
    name: openbao-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: alertmanager-webhook-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        webhook-url: "{{ .webhook_url }}"
  data:
    - secretKey: webhook_url
      remoteRef:
        key: shared/notifications/discord
        property: url
