[uwsgi]
uid = searxng
gid = searxng

disable-logging = true
log-5xx = true

workers = 4
threads = 4

buffer-size = 8192
max-requests = 1000
lazy-apps = true
master = true
enable-threads = 4

static-map = /static=/usr/local/searxng/searx/static
static-expires = /* 86400
static-gzip-all = True
offload-threads = 2

cache2 = name=searxngcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
