---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret seerr-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-cluster-secretstore
  target:
    name: *secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        API_KEY: "{{ .seerr_api_key }}"
        # --
        DB_HOST: downloads-postgres-pooler.downloads.svc.cluster.local
        DB_PORT: "5432"
        DB_NAME: seerr
        DB_USER: seerr
        DB_PASS: "{{ .DB_PASSWORD }}"
        # --
        INIT_POSTGRES_DBNAME: seerr
        INIT_POSTGRES_HOST: downloads-postgres-pooler.downloads.svc.cluster.local
        INIT_POSTGRES_PASS: "{{ .DB_PASSWORD }}"
        INIT_POSTGRES_USER: seerr

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "DB_PASSWORD"

  data:
    - secretKey: seerr_api_key
      remoteRef:
        key: downloads/seerr/config
        property: api_key
