---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret configarr-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-cluster-secretstore
  target:
    name: *secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        SONARR_API_KEY: "{{ .sonarr_api_key }}"
        RADARR_API_KEY: "{{ .radarr_api_key }}"
        EBOOKSHELF_API_KEY: "{{ .ebookshelf_api_key }}"
  data:
    - secretKey: sonarr_api_key
      remoteRef:
        key: downloads/sonarr/config
        property: api_key
    - secretKey: radarr_api_key
      remoteRef:
        key: downloads/radarr/config
        property: api_key
    - secretKey: ebookshelf_api_key
      remoteRef:
        key: downloads/ebookshelf/config
        property: api_key
