---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: ${APP}-postgres-backup
  namespace: ${NAMESPACE}
spec:
  configuration:
    destinationPath: ${POSTGRES_BACKUP_PATH:=s3://postgresql-backups/${APP}}
    endpointURL: ${POSTGRES_BACKUP_ENDPOINT:=http://minio.storage.svc.cluster.local:9000}
    s3Credentials:
      accessKeyId:
        name: ${APP}-postgres-minio
        key: MINIO_ACCESS_KEY
      secretAccessKey:
        name: ${APP}-postgres-minio
        key: MINIO_SECRET_KEY
    wal:
      compression: ${POSTGRES_BACKUP_WAL_COMPRESSION:=zstd}
      maxParallel: ${POSTGRES_BACKUP_WAL_MAX_PARALLEL:=2}
    data:
      compression: ${POSTGRES_BACKUP_DATA_COMPRESSION:=gzip}
      jobs: ${POSTGRES_BACKUP_DATA_JOBS:=2}
  retentionPolicy: ${POSTGRES_BACKUP_RETENTION:=20d}
