---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: weave-gitops
  namespace: flux-system
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Weave GitOps
    gethomepage.dev/group: Services
    gethomepage.dev/icon: weave-gitops.svg
    gethomepage.dev/description: Flux dashboard · LAN only
    kustomize.toolkit.fluxcd.io/substitute: "true"
spec:
  hostnames: ["gitops.${SECRET_DOMAIN}"]
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: weave-gitops
          port: 9001
      matches:
        - path:
            type: PathPrefix
            value: /