---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace downloaders
components:
  - ../../components/common
  - ../../components/pod-security/privileged
  - ../../components/flux/alerts
resources:
  - ./nzbget/ks.yaml
  - ./qbittorrent/ks.yaml
