---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-power-tools-db
  namespace: media
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-cluster-secretstore
  target:
    name: immich-power-tools-db
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: "{{ .db_username }}"
        password: "{{ .db_password }}"
  data:
    - secretKey: db_username
      remoteRef:
        key: media/immich-power-tools/config
        property: db_username
    - secretKey: db_password
      remoteRef:
        key: media/immich-power-tools/config
        property: db_password
