---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-power-tools-secret
  namespace: media
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-cluster-secretstore
  target:
    name: immich-power-tools-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        IMMICH_URL: "http://immich-server.media.svc.cluster.local:2283"
        IMMICH_API_KEY: "{{ .api_key }}"
        DB_HOST: "immich-postgres-rw.media.svc.cluster.local"
        DB_PORT: "5432"
        DB_DATABASE_NAME: "immich"
        DB_USERNAME: "{{ .db_username }}"
        DB_PASSWORD: "{{ .db_password }}"
        JWT_SECRET: "{{ .jwt_secret }}"
  data:
    - secretKey: api_key
      remoteRef:
        key: media/immich/api-keys
        property: power_tools
    - secretKey: db_username
      remoteRef:
        key: media/immich-power-tools/config
        property: db_username
    - secretKey: db_password
      remoteRef:
        key: media/immich-power-tools/config
        property: db_password
    - secretKey: jwt_secret
      remoteRef:
        key: media/immich-power-tools/config
        property: jwt_secret
