  # yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app listenarr

spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  values:
    controllers:
      listenarr:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            fsGroup: 1001
            fsGroupChangePolicy: "OnRootMismatch"
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault

        containers:
          app:
            image:
              repository: ghcr.io/therobbiedavis/listenarr
              tag: canary-0.2.47@sha256:c917f40d7a79f89e10ecef754cf4fd189f018a55ad561f3a8f95f6766e47086b
            env:
              TZ:  "${TIMEZONE}"
              LISTENARR_LOG_LEVEL: info
              LISTENARR_PUBLIC_URL: https://listenarr.${SECRET_DOMAIN}
              ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"

            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 4545
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 30
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes

            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    persistence:
      config:
        existingClaim: *app
        globalMounts:
        - path: /app/config

      media:
        type: nfs
        path: "/mnt/${SECRET_NFS_SHARE}/media"
        server: "${SECRET_NFS_SERVER}"
        globalMounts:
          - path: /data/media

      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
