# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret rreading-glasses-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-cluster-secretstore
  target:
    name: *secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        HARDCOVER_API_KEY: "{{ .hardcover_api_key }}"
        INIT_POSTGRES_DBNAME: rreading_glasses
        INIT_POSTGRES_HOST: downloads-postgres-pooler.downloads.svc.cluster.local
        INIT_POSTGRES_USER: "rreading_glasses"
        INIT_POSTGRES_PASS: "{{ .db_password }}"

  data:
    - secretKey: hardcover_api_key
      remoteRef:
        key: downloads/rreading-glasses/config
        property: api_key
    - secretKey: db_password
      remoteRef:
        key: downloads/rreading-glasses/config
        property: db_password
