---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: influxdb
  namespace: database
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: InfluxDB
    gethomepage.dev/group: Services
    gethomepage.dev/icon: influxdb.svg
    gethomepage.dev/description: Time series database · LAN only
    kustomize.toolkit.fluxcd.io/substitute: "true"
spec:
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  hostnames:
    - "influxdb.${SECRET_DOMAIN}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: influxdb
          port: 8086
          weight: 100