---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret lidarr-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-cluster-secretstore
  target:
    name: *secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        LIDARR__AUTH__APIKEY: "{{ .lidarr_api_key }}"
        LIDARR__POSTGRES__HOST: downloads-postgres-pooler.downloads.svc.cluster.local
        LIDARR__POSTGRES__PORT: "5432"
        LIDARR__POSTGRES__MAINDB: lidarr
        LIDARR__POSTGRES__USER: lidarr
        LIDARR__POSTGRES__PASSWORD: "{{ .DB_PASSWORD }}"
        # --
        INIT_POSTGRES_DBNAME: lidarr
        INIT_POSTGRES_HOST: downloads-postgres-pooler.downloads.svc.cluster.local
        INIT_POSTGRES_PASS: "{{ .DB_PASSWORD }}"
        INIT_POSTGRES_USER: lidarr

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "DB_PASSWORD"

  data:
    - secretKey: lidarr_api_key
      remoteRef:
        key: downloads/lidarr/config
        property: api_key
