---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/database/cluster
patches:
  - target:
      kind: ObjectStore
      name: postgres-backup
    patch: |-
      - op: replace
        path: /metadata/name
        value: ${APP}-postgres-backup
